name: Pylint and Black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask gitpython psutil numpy diffusers black spacy
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Formatting code with Black
      run: |
        git ls-files -- '*.py' | xargs black --check --diff
